csk/urls.py
from csk.views import *
from django.urls import path
app_name='csk'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcb'
urlpatterns=[
    path('hardhik/',hardhik,name='hardhik'),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def hardhik(request):
    return render(request,'hardhik.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dhoni</title>
</head>
<body>
    <center>
    <h1>welcome to dhoni HTML page</h1>
    <a href="{% url 'rcb:hardhik' %}">specific url mapping</a>
    <h1> welcome to hardhik html page</h1>
    </center>
</body>
</html>

templates/hardhik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>virat</title>
</head>
<body>
    <center>
    <h1>welcome to virat html page</h1>
    <a href="{% url 'csk:dhoni' %}">specific url mapping</a>
    <h2>welcome to dhoni html page</h2>
    </center>
</body>
</html>